import Image from "next/image";
import React from "react";
import HeaderLink from "../components/HeaderLink";
import ExploreIcon from "@mui/icons-material/Explore";
import GroupIcon from "@mui/icons-material/Group";
import OndemandVideoSharpIcon from "@mui/icons-material/OndemandVideoSharp";
import BusinessCenterIcon from "@mui/icons-material/BusinessCenter";
import ArrowForwardIosRoundedIcon from "@mui/icons-material/ArrowForwardIosRounded";
import Head from "next/head";
import { getProviders, signIn, signOut } from "next-auth/react";

function Home({ providers }) {

  return (
    <div className="header-area header-sass ">
        <Head>
        <title>Sproutly</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-around items-center pb-4 bg-transparent mt-[-2rem]">
        <div className="relative w-56 h-40 mt-[0rem]">
          <Image
            src="/images/logo1.svg"
            alt="logo"
            layout="fill"
            objectFit="contain"
          />
        </div>

        <div className="flex items-center sm:divide-x divide-gray-300">
          <div className="hidden sm:flex space-x-8 pr-4">
            <HeaderLink Icon={ExploreIcon} text="Discover" />
            <HeaderLink Icon={GroupIcon} text="People" />
            <HeaderLink Icon={OndemandVideoSharpIcon} text="Learning" />
            <HeaderLink Icon={BusinessCenterIcon} text="Jobs" /> 
            <p onClick={signOut}>Signout</p>
          </div>

          {Object.values(providers).map((provider) => (
            <div key={provider.name}>
              <div className="pl-4">
                <button
                  className="text-blue-700 font-semibold rounded-full border border-blue-700 px-5 py-1.5 transition-all hover:border-2"
                  onClick={() => signIn(provider.id, { callbackUrl: "/" })}
                >
                  Sign in
                </button>
              </div>
            </div>
          ))}

        </div>
      </header>

      <main className="">
      <div className="pt-[10px] xl:hidden flex flex-col justify-center items-center text-center sm:text-left">
      <div className="header-inner flex-col">
         
         <h1 className="title lg:!text-6xl md:!text-6xl !text-4xl sm:!text-5xl px-4">    Meet. Connect. Share.</h1>
         <p className="!text-white px-4 flex items-center mx-auto justify-center">A professional community designed to help you grow.</p>
         <div className="flex items-center mx-auto justify-center pt-3">
           <button  className="bg-white text-blue-700 font-semibold rounded-full border border-white-700 px-5 py-1.5 transition-all hover:border-2">Search for a job</button>
         </div>
       </div>
      
       
        <div className="relative w-[320px] h-[320px] lg:w-[600px] lg:h-[600px] md:w-[500px] md:h-[500px] sm:w-[400px] sm:h-[400px] mt-[2rem] mb-[-10rem]">
        <Image 
       src="/images/01.png"
       alt="hero image"
       layout="fill"
       objectFit="contain"
       className=""
       priority
       />
        </div>
        <div className="shape pb-[200px]" />
  <div className="shape-02 " />
    </div>


<div className="pt-[205px] hidden xl:flex">
  <div className="sass-bg-img-02" style={{backgroundImage: 'url(/images/bg.png)'}} />
  <div className="sass-bg-img" style={{backgroundImage: 'url(/images/01.png)'}} />
  <div className="shape pb-[200px]" />
  <div className="shape-02 " />
  <div className="main-container">
    <div className="grid grid-cols-3 gap-3">
      <div className="col-span-2">
        <div className="header-inner mt-[-5rem] ">
          {/* header inner */}
          <h1 className="title">    Meet. <br/> Connect. <br/> Share.</h1>
          <p className="!text-white">A professional community designed to help you grow.</p>
          <div className="btn-wrapper pt-3">
            <button  className="bg-white text-blue-700 font-semibold rounded-full border border-white-700 px-5 py-1.5 transition-all hover:border-2">Join to start sprouting</button>
          </div>
        </div>
        {/* //.header inner */}
      </div>
    </div>
  </div>
</div>

      </main>
    </div>
  );
}

export default Home;

export async function getServerSideProps(context) {
    const providers = await getProviders();
  
    return {
      props: {
        providers,
      },
    };
  }
